### ISSUE TITLE
3rd Party App Catalog Support Analysis

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-catalog#237]
### Problem

Can we get more data to understand the commitment to keeping lights vs enhancing and supporting these apps? The idea would be able to provide some data and estimates of effort to do more meaningful work with the app catalog. In doing this analysis, it would be good to decide which apps should still be available in the app catalog.

### Acceptance Criteria 

- [x] Add aggregate charts for 3rd Party Catalog EOL Dashboard to understand the usage and github activity
- [x] Look at enhancements and bugs and get sense of total effort and commitment needed to execute on these backlogs.
- [ ] Provide a recommendation on how to proceed.

**Comment by jpvajda** [comment]
I wonder if we can terraform the creation of these individual dashboard widgets for each app? 🤔 
https://newrelic.com/blog/how-to-relic/how-to-create-syslog-dashboard-using-new-relic-terraform

**Comment by jpvajda** [comment]
I thinking getting  a count of all bugs and enhancements by repository would be useful, I think we can use the Github API to return this information based on the issue label.

https://docs.github.com/en/rest/reference/issues#list-labels-for-an-issue

**Comment by jpvajda** [comment]
`repo is here:` https://github.com/jpvajda/labelparse  

I'm seeing this error after running the program several times:  ```Traceback (most recent call last):
  File "/Users/jvajda/Documents/Github/DevEn/labelparse/labelparse.py", line 34, in <module>
    print_issue(issue)
  File "/Users/jvajda/Documents/Github/DevEn/labelparse/labelparse.py", line 21, in print_issue
    print('Repo: ' + issue['repository_url'])
TypeError: string indices must be integers```

I'm wondering if: 

1. Github is rate limiting these requests?
2. I need to use an asnyc approach(https://www.twilio.com/blog/asynchronous-http-requests-in-python-with-aiohttp)
3. or if there is a memory issue...

**Comment by jpvajda** [comment]
<img width="251" alt="Screen Shot 2021-05-05 at 2 38 45 PM" src="https://user-images.githubusercontent.com/1395158/117206102-a7247b00-adaf-11eb-9a2a-00256f110e78.png">
